POST http://localhost:8080/events
content-type: application/json

{
    "name":"Test Event 2",
    "description": "A test event",
    "location" : "Test location",
    "datetime" : "2025-01-01T15:30:00.000Z"
}
